# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BOT build and publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        LOGIN: ${{ secrets.LOGIN_DEVOPS }}
        PASSWORD: ${{ secrets.PWD_DEVOPS }}
      run: |
        echo "LOGIN=$LOGIN
              PASSWORD=$PASSWORD" > ./scraper/.env
    - shell: bash
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMANDE: ${{ secrets.COMMAND_DEVOPS }}
      run: |
        echo "BOT_TOKEN=$BOT_TOKEN
              COMMANDE=$COMMANDE" > ./bot_discord/.env
              
    - shell : bash
      run : |
        cd .. && 
        tar -czf ./scraper-bot.tar.gzip ./scrap-cesi-tp
        
    - shell : bash
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }} 
      run : |
        echo "$SSH_KEY" > key.pem && 
        chmod 400 key.pem &&
        ls && cat key.pem &&
        ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$AWS_INSTANCE_ADDR 'bash -s' < ./scripts/clean-folder.sh
                  
    - shell : bash
      env:
        AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }} 
      run : |
        ls -a ..
        scp -i key.pem -o StrictHostKeyChecking=no ../scraper-bot.tar.gzip ec2-user@$AWS_INSTANCE_ADDR:/home/ec2-user/scraper-bot.tar.gzip && 
        ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$AWS_INSTANCE_ADDR tar -xzf /home/ec2-user/scraper-bot.tar.gzip
        
    - shell : bash
      env:
        AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }} 
      run : |
         ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$AWS_INSTANCE_ADDR docker-compose -f /home/ec2-user/scrap-cesi-tp/docker-compose.yaml up --build -d --always-recreate
        
        
    
