name: Build and deploy no-devops

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        name: Create scraper .env
        env:
          LOGIN: ${{ secrets.LOGIN_NODEVOPS }}
          PASSWORD: ${{ secrets.PWD_NODEVOPS }}
        run: |
          echo "LOGIN=$LOGIN
                PASSWORD=$PASSWORD" > ./scraper/.env

      - shell: bash
        name: Create bot .env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMANDE: ${{ secrets.COMMAND_NODEVOPS }}
        run: |
          echo "BOT_TOKEN=$BOT_TOKEN
                COMMANDE=$COMMANDE" > ./bot_discord/.env

      - shell : bash
        name: Package archive
        run : |
          cd .. &&
          tar -czf ./scraper-bot.tar.gzip ./scrap-cesi-tp

      - shell : bash
        name: Create ssh key and remove old package
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }}
          DOCKER_COMPOSE_YML_PATH: /home/ec2-user/scrap-cesi-tp/docker-compose.nodevops.yaml
        run : |
          echo "$SSH_KEY" > key.pem &&
          chmod 400 key.pem &&
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$AWS_INSTANCE_ADDR 'bash -s' < './scripts/clean-folder.sh'

      - shell : bash
        name: Copy and untar package
        env:
          AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }}
        run : |
          scp -i key.pem -o StrictHostKeyChecking=no ../scraper-bot.tar.gzip ec2-user@$AWS_INSTANCE_ADDR:/home/ec2-user/scraper-bot.tar.gzip &&
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$AWS_INSTANCE_ADDR mkdir -p /home/ec2-user/scraper-bot-nodevops && tar -C /home/ec2-user/scraper-bot-nodevops -xzf /home/ec2-user/scraper-bot-nodevops.tar.gzip

      - shell : bash
        name: Deploy with docker-compose
        env:
          AWS_INSTANCE_ADDR: ${{ secrets.AWS_INSTANCE_ADDR }}
          DOCKER_COMPOSE_YML_PATH: /home/ec2-user/scrap-cesi-tp/docker-compose.nodevops.yaml
        run : |
          ./scripts/deploy.sh



