# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BOT build and publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        LOGIN: ${{ secrets.LOGIN_DEVOPS }}
        PWD: ${{ secrets.PWD_DEVOPS }}
      run: |
        echo "LOGIN=$LOGIN
              PWD=$PWD" > ./scraper/.env
    - shell: bash
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMANDE: ${{ secrets.COMMAND_DEVOPS }}
      run: |
        echo "BOT_TOKEN=$BOT_TOKEN
              COMMANDE=$COMMANDE" > ./bot_discord/.env
              
